fail failures

diff --git a/.github/workflows/validate-renovate.yaml b/.github/workflows/validate-renovate.yaml
--- a/.github/workflows/validate-renovate.yaml
+++ b/.github/workflows/validate-renovate.yaml
@@ -18,4 +18,8 @@ jobs:
           LOG_FORMAT: json
         run: |
           docker run --rm -i -v $(pwd):$(pwd) -w $(pwd) -e LOG_LEVEL -e LOG_FORMAT -e RENOVATE_TOKEN \
-            renovate/renovate:slim ${{ github.repository }} --dry-run 
+            renovate/renovate:slim ${{ github.repository }} --dry-run > renovate.jsonl
+          if grep failed renovate.jsonl;
+            echo "::error ::$(grep failed renovate.jsonl| jq -r .msg)"
+            exit 1
+          fi
